In [54]:
import pandas as pd

df = pd.read_csv("messy_sales.csv")

print("Dataset Shape:", df.shape)

display(df.head(10))

print("Column Data Types:")
print(df.dtypes)

Dataset Shape: (300, 6)

   order_id        date   product  price  qty    zip
0      1254  04/06/2026       mug  11.36    4  60614
1      1057  2026-05-30   charger  14.79    3  30303
2      1150  05/06/2026       mug   5.50    1  10001
3      1066  05/30/2026  notebook    NaN    1  98101
4      1114  04/06/2026    webcam  45.59    4  90405
5      1280  04/22/2026   pen set    NaN    4  30303
6      1204  04/18/2026   charger   8.41    2   2134
7      1249  2026-05-15  keyboard  75.04    4  90405
8      1037  2026-05-19       mug   9.31    2  60614
9      1177  2026-05-13       mug  10.11    3  90210

Column Data Types:
order_id      int64
date            str
product         str
price       float64
qty           int64
zip           int64
dtype: object

In [42]:
### Data Observations

In [43]:
print("Missing Values Before Cleaning:")

print(df.isna().sum())

Missing Values Before Cleaning:
order_id     0
date         0
product      0
price       12
qty          0
zip          0
dtype: int64

In [44]:
median_price = df["price"].median()

print("Median Price:", median_price)

df["price"] = df["price"].fillna(median_price)

print("Missing Values After Filling Prices:")
print(df.isna().sum())

Median Price: 37.53
Missing Values After Filling Prices:
order_id    0
date        0
product     0
price       0
qty         0
zip         0
dtype: int64

In [45]:
print("Original Shape:", df.shape)

duplicate_count = df.duplicated().sum()

print("Duplicate Rows Found:", duplicate_count)

df = df.drop_duplicates()

print("New Shape:", df.shape)

Original Shape: (300, 6)
Duplicate Rows Found: 8
New Shape: (292, 6)

In [46]:
df["zip"] = df["zip"].astype(str).str.zfill(5)

print("Updated ZIP Codes:")
print(df["zip"].head(10))

print("ZIP Code Data Type:")
print(df["zip"].dtype)

Updated ZIP Codes:
0    60614
1    30303
2    10001
3    98101
4    90405
5    30303
6    02134
7    90405
8    60614
9    90210
Name: zip, dtype: str
ZIP Code Data Type:
str

In [47]:
df["date"] = pd.to_datetime(
    df["date"],
    format="mixed"
)

print("Updated Column Types:")
print(df.dtypes)

display(df.head(10))

Updated Column Types:
order_id             int64
date        datetime64[us]
product                str
price              float64
qty                  int64
zip                    str
dtype: object

   order_id       date   product  price  qty    zip
0      1254 2026-04-06       mug  11.36    4  60614
1      1057 2026-05-30   charger  14.79    3  30303
2      1150 2026-05-06       mug   5.50    1  10001
3      1066 2026-05-30  notebook  37.53    1  98101
4      1114 2026-04-06    webcam  45.59    4  90405
5      1280 2026-04-22   pen set  37.53    4  30303
6      1204 2026-04-18   charger   8.41    2  02134
7      1249 2026-05-15  keyboard  75.04    4  90405
8      1037 2026-05-19       mug   9.31    2  60614
9      1177 2026-05-13       mug  10.11    3  90210

In [48]:
negative_rows = df[df["qty"] < 0]

print("Negative Quantity Records:")
display(negative_rows)

print("Number of Negative Records:", len(negative_rows))

Negative Quantity Records:

     order_id       date    product  price  qty    zip
202      1140 2026-04-18     webcam  38.69   -5  98101
262      1233 2026-05-09  desk lamp  22.64   -4  10001
297      1025 2026-04-27   keyboard  47.30   -2  02116

Number of Negative Records: 3

In [49]:
# Keep negative quantities as a possible returns.
# No rows are removed and changed.

print("Negative quantities retained:", (df["qty"] < 0).sum())

print("Dataset Shape:", df.shape)

Negative quantities retained: 3
Dataset Shape: (292, 6)

In [50]:
# Negative Quantity

In [51]:
df.to_csv("sales_clean.csv", index=False)

print("Cleaned sales data saved successfully!")

print("Final Shape:", df.shape)

display(df.head(10))

Cleaned sales data saved successfully!
Final Shape: (292, 6)

   order_id       date   product  price  qty    zip
0      1254 2026-04-06       mug  11.36    4  60614
1      1057 2026-05-30   charger  14.79    3  30303
2      1150 2026-05-06       mug   5.50    1  10001
3      1066 2026-05-30  notebook  37.53    1  98101
4      1114 2026-04-06    webcam  45.59    4  90405
5      1280 2026-04-22   pen set  37.53    4  30303
6      1204 2026-04-18   charger   8.41    2  02134
7      1249 2026-05-15  keyboard  75.04    4  90405
8      1037 2026-05-19       mug   9.31    2  60614
9      1177 2026-05-13       mug  10.11    3  90210

In [52]:
print("FINAL DATA QUALITY CHECK")

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isna().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nColumn Data Types:")
print(df.dtypes)

print("\nZIP Code Lengths:")
print(df["zip"].str.len().value_counts())

print("\nNegative Quantities:")
print((df["qty"] < 0).sum())

FINAL DATA QUALITY CHECK

Dataset Shape:
(292, 6)

Missing Values:
order_id    0
date        0
product     0
price       0
qty         0
zip         0
dtype: int64

Duplicate Rows:
0

Column Data Types:
order_id             int64
date        datetime64[us]
product                str
price              float64
qty                  int64
zip                    str
dtype: object

ZIP Code Lengths:
zip
5    292
Name: count, dtype: int64

Negative Quantities:
3

In [53]:
# AI Tool Usage
# AI Tool: ChatGPT (OpenAI)
# Assistance with understanding Python pandas
# commands, debugging, and checking data-cleaning steps.