In [8]:
# Module 3 Lab 2: Hands on problem 2.
# In is Lab i will analyze crime
# data from 50 U.S. states
# identifying suspicious values and
# calculating summary statistics.
# I will determine if flagged values # are unusual or impossible.
# I will document my decisions
# before making changes to my dataset.

In [9]:
import pandas as pd

df = pd.read_csv("usarrests.csv")

df.head()

   Unnamed: 0  Murder  Assault  UrbanPop
0     Alabama    13.2    236.0        58
1      Alaska    10.0    263.0        48
2     Arizona     8.1    294.0        80
3    Arkansas     8.8    190.0        50
4  California     9.0    276.0        91

In [10]:
df = df.rename(columns={"Unnamed: 0": "State"})

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

df.head()

Dataset shape: (50, 4)

Column names:
['State', 'Murder', 'Assault', 'UrbanPop']

        State  Murder  Assault  UrbanPop
0     Alabama    13.2    236.0        58
1      Alaska    10.0    263.0        48
2     Arizona     8.1    294.0        80
3    Arkansas     8.8    190.0        50
4  California     9.0    276.0        91

In [11]:
summary = df[["Murder", "Assault", "UrbanPop"]].describe()

summary

         Murder     Assault   UrbanPop
count  50.00000   49.000000   50.00000
mean    7.78800  182.183673   74.20000
std     4.35551  130.877435   73.40828
min     0.80000   45.000000    6.00000
25%     4.07500  109.000000   53.25000
50%     7.25000  159.000000   66.00000
75%    11.25000  249.000000   77.75000
max    17.40000  879.000000  570.00000

In [12]:
extreme_assault = df[
    df["Assault"] > 500
]

extreme_assault

             State  Murder  Assault  UrbanPop
39  South Carolina    14.4    879.0        48

In [13]:
low_urban = df[
    df["UrbanPop"] < 20
]

low_urban

       State  Murder  Assault  UrbanPop
31  New York    11.1    254.0         6

In [14]:
print("Missing values by column:")
print(df.isnull().sum())

print("\nRows with missing values:")
display(df[df.isnull().any(axis=1)])

Missing values by column:
State       0
Murder      0
Assault     1
UrbanPop    0
dtype: int64

Rows with missing values:

     State  Murder  Assault  UrbanPop
9  Georgia    17.4      NaN        60

In [15]:
# Outlier  Analysis
# Flag 1: Iowa - UrbanPop = 570% (impossible)
# Urban population percentage cannot exceed 100%.
# Flag 2: South Carolina - Assault = 879 (extremely high)
# Flag 3: New York - UrbanPop = 6% (possible)
# For New York unusually low, could be a data entry error.
# Check original data entry error.
# Georgia Data Quality Issue - Missing Assault Value
# Data quality issue rather than an outlier.

In [16]:
import pandas as pd

# Create a cleaning log
cleaning_log = pd.DataFrame({
    "State": [
        "Iowa",
        "South Carolina",
        "New York",
        "Georgia"
    ],
    "Column": [
        "UrbanPop",
        "Assault",
        "UrbanPop",
        "Assault"
    ],
    "Original Value": [
        570, 879, 6, None
    ],
    "Classification": [
        "Impossible",
        "Extreme",
        "Suspicious",
        "Missing"
    ],
    "Action": [
        "Verify before correction",
        "Investigate before changing",
        "Verify against source",
        "Keep missing until verified"
    ]
})

# Display the cleaning log
cleaning_log

,State,Column,Original Value,Classification,Action
0,Iowa,UrbanPop,570.0,Impossible,Verify before correction
1,South Carolina,Assault,879.0,Extreme,Investigate before changing
2,New York,UrbanPop,6.0,Suspicious,Verify against source
3,Georgia,Assault,NaN,Missing,Keep missing until verified